### ISSUE TITLE
for jetpack 4.4 

### ISSUE THREAD

**Issue by diamondbarcode** [JetsonHacksNano/buildOpenCV#9]
hi, is there any update for jetpack 4.4 yet with the latest OpenCV? for some reason my copencv does not support cuda ..

jetson@jetson-agx:~/jetsonUtilities$ ./jetsonInfo.py
NVIDIA Jetson AGX Xavier [16GB]
 L4T 32.4.3 [ JetPack 4.4 ]
   Ubuntu 18.04.5 LTS
   Kernel Version: 4.9.140-tegra
 CUDA 10.2.89
   CUDA Architecture: 7.2
 OpenCV version: 4.1.1
   OpenCV Cuda: NO
 CUDNN: 8.0.0.180
 TensorRT: 7.1.3.0
 Vision Works: 1.6.0.501
 VPI: 0.3.7

**Comment by diamondbarcode** [comment]
i found the one made for jetpack 4.4

**Comment by WQ-2001-mc** [comment]
> i found the one made for jetpack 4.4

which one? share the links, thanks. I also use AGX Xavier
